---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)

questions <- read_csv("questions.csv")
answers <- read_csv("answers.csv")
tags <- read_csv("tags.csv")
question_tags <- read_csv("question_tags.csv")

questions
answers
tags
question_tags
```

1.1

```{r}
questions %>%
  left_join(question_tags, by = c("id"="question_id"))
```

1.2
```{r}
questions %>%
  left_join(question_tags, by = c("id"="question_id")) %>%
  left_join(tags, by= c("tag_id"="id"))
```

1.3
```{r}
questions %>%
  left_join(question_tags, by = c("id"="question_id")) %>%
  left_join(tags, by= c("tag_id"="id")) %>%
  replace_na(list(tag_name="only-r"))
```

1.4

```{r}
question_with_tags <- questions %>%
  left_join(question_tags, by = c("id"="question_id")) %>%
  left_join(tags, by= c("tag_id"="id")) %>%
  replace_na(list(tag_name="only-r"))
  
```


2.1, 2.2 y 2.3

```{r}
question_with_tags %>%
  group_by(tag_name) %>%
  summarize(mean_score = mean(score)) %>%
  arrange(desc(mean_score))
```

3.1

```{r}
questions %>%
  inner_join(answers, by= c("id" = "question_id"), suffix=c("_question", "_answer"))
```

3.2

```{r}
questions %>%
  inner_join(answers, by= c("id" = "question_id"), suffix=c("_question", "_answer")) %>%
  mutate(gap = creation_date_answer - creation_date_question)
```

4.1

```{r}
answer_counts <- answers %>%
  count(question_id) %>%
  arrange(desc(n))

answer_counts
```

4.2

```{r}
questions %>%
  left_join(answer_counts, by=c("id" = "question_id"))
```

4.3 y 4.4
```{r}
question_answer_counts <- questions %>%
  left_join(answer_counts, by=c("id" = "question_id")) %>%
  replace_na(list(n=0))

question_answer_counts
```

5.1 y 5.2
```{r}
question_tags %>%
  inner_join(question_answer_counts, by=c("question_id" = "id")) %>%
  inner_join(tags, by= c("tag_id" = "id")) %>%
  arrange(desc(n))
```

